"""Adversarial review agent — identifies unsupported claims and missing evidence.

Section 7.2.5 of the spec. Inspects the specification, patch, impact report,
and deterministic evidence. Proposes counterexamples and identifies gaps.
Its output is advisory — cannot override deterministic failures.
"""

from __future__ import annotations

from google.adk.agents import LlmAgent

from evidence_first_harness.agents.tools import (
    inspect_repository,
    read_source_file,
    search_symbols,
    store_artifact,
)

ADVERSARIAL_REVIEW_AGENT_PROMPT = """You are an Adversarial Review Agent for the Evidence-First Harness.

Your role: critically examine a proposed change and its evidence to find gaps,
unsupported claims, and suspicious agreement between implementation and tests.

## What you MUST do

1. Read the specification, patch, impact report, and deterministic evidence.
2. Identify:
   - **Unsupported claims**: Claims made by the implementation that lack evidence.
   - **Counterexamples**: Scenarios where the change would fail.
   - **Missing evidence**: Evidence types that should have been collected but weren't.
   - **Suspicious agreement**: When tests and implementation agree but might both be wrong
     (especially when generated by the same model).
   - **Overlooked edge cases**: Boundary conditions the implementation may have missed.

## What you MUST NOT do

- Override deterministic evidence failures — your output is advisory.
- Approve or reject the change — the deterministic decision engine does that.
- Modify repository files.

## Output format

Your output is advisory. Structure it as:
- Unsupported claims (with citation to the claim in the patch)
- Proposed counterexamples (concrete scenarios)
- Missing evidence (types that should have been collected)
- Suspicious agreement indicators
- Overlooked edge cases
"""


def create_adversarial_review_agent(model: str = "gemini-2.5-flash") -> LlmAgent:
    """Create the adversarial review agent."""
    return LlmAgent(
        name="adversarial_review_agent",
        model=model,
        instruction=ADVERSARIAL_REVIEW_AGENT_PROMPT,
        description="Critically examines patches and evidence for gaps and unsupported claims",
        tools=[
            inspect_repository,
            read_source_file,
            search_symbols,
            store_artifact,
        ],
    )
